/robot_news_station_bb8:
  ros__parameters:
    robot_name: "BB8"
    timer_period: 4.0

/robot_news_station_c3po:
  ros__parameters:
    robot_name: "C3PO"
    timer_period: 2.0

/robot_news_station_daneel:
  ros__parameters:
    robot_name: "Daneel"
    timer_period: 12.0

/robot_news_station_giskard:
  ros__parameters:
    robot_name: "Giskard"
    timer_period: 8.0

/robot_news_station_jander:
  ros__parameters:
    robot_name: "Jander"
    timer_period: 5.0
